### ISSUE TITLE
Editable and Draggable Text in Your Meme maker app.

### ISSUE THREAD

**Issue by Shivam-Shrivastav** [Tushargupta9800/Meme_maker_flutter_complete_app#1]
Hey Tushar, I am Shivam, I have a suggestion for you, you could use an editable and draggable text to move your text in the anywhere in the scaffold by simply dragging the written text.
I have a dart file for editable and draggable text in my [Flutter basic repository](https://github.com/starboy2102/Flutter-Basics) you can check that out.

By the way I have a problem in one of my flutter project can you help me in that?

Thank you.

**Comment by Tushargupta9800** [comment]
Ok, I will help just msg me on LinkedIn https://www.linkedin.com/in/tushar-gupta-6100561a0 , mail me on iit2019043@iiita.ac.in or just give me ur whatsapp no. I'll msg u.. And thanks for your suggestion I'll definitely look into that.
